version: '3.7'


services:
  django-app:
    build: ./app
    volumes:
      - static_volume:/usr/src/app/staticfiles/
    ports:
      - 8000
    command: gunicorn -w 3 -b :8000 hello_django.wsgi:application

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - django-app
    volumes:
      - static_volume:/usr/src/app/staticfiles/


volumes:
  static_volume:
